# Generated by Django 5.1.4 on 2024-12-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanager",
            name="date",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="eventmanager",
            name="time",
            field=models.CharField(max_length=10),
        ),
    ]
